### ISSUE TITLE
mern-login-register-dashboard

### ISSUE THREAD

**Issue by berthutapea** [berthutapea/mern-login-register-dashboard#1]
![img-1](https://github.com/berthutapea/mern-login-register-dashboard/assets/111676859/f44c3e0e-a82b-4797-a1d5-e565337245d8)
![img-2](https://github.com/berthutapea/mern-login-register-dashboard/assets/111676859/92131144-46a1-4b74-af0f-f817df506321)
![img-3](https://github.com/berthutapea/mern-login-register-dashboard/assets/111676859/6f6051df-6738-4f53-a977-4955825dbf11)

**Comment by 05-yuvraj-singh** [comment]
@berthutapea hey i can implement this feature via mongo express and node if you just assign me the issue  :)
